(()=>{'use strict';const $=id=>document.getElementById(id);let texts={},published={},revision=0,selection=null,dirty=false,busy=false;const notice=t=>$('notice').textContent=t;
 async function api(action,body){const r=await fetch('/api/editor/'+action,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json','X-Editor-Action':'1'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Service indisponible.');return d;}
 function send(){if($('app').contentWindow)$('app').contentWindow.postMessage({type:'echo-edit-preview',texts,enabled:true},location.origin);$('count').textContent=Object.keys(texts).length+' texte(s) personnalisé(s).'+(dirty?' Modifications non enregistrées.':'');}
 async function load(){const d=await api('draft');texts=d.texts;published=d.published;revision=d.revision;dirty=false;send();}
 async function guard(fn){if(busy)return;busy=true;document.querySelectorAll('.actions button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message);}finally{busy=false;document.querySelectorAll('.actions button').forEach(b=>b.disabled=false);$('apply').disabled=$('default').disabled=!selection;}}
 async function save(){const d=await api('save',{revision,texts});revision=d.revision;dirty=false;send();notice('Brouillon enregistré. Rien n’a été publié.');}
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('app').contentWindow)return;if(e.data?.type==='echo-edit-ready')send();if(e.data?.type==='echo-edit-select'){selection=e.data;$('selection').textContent='Texte — '+selection.section;$('original').textContent=selection.original;$('replacement').value=texts[selection.key]?.text??selection.original;$('replacement').disabled=$('apply').disabled=$('default').disabled=false;}});
 $('apply').onclick=()=>{if(!selection)return;const text=$('replacement').value.trim();if(!text||text.length>6000){notice('Saisir entre 1 et 6 000 caractères.');return;}texts[selection.key]={original:selection.original,section:selection.section,text};dirty=true;send();notice('Modification ajoutée au brouillon, non publiée.');};
 $('default').onclick=()=>{if(!selection)return;delete texts[selection.key];dirty=true;$('replacement').value=selection.original;send();};
 $('save').onclick=()=>guard(save);$('preview').onclick=()=>{send();notice('La prévisualisation affiche le brouillon. Vérifie chaque onglet concerné avant de publier.');};
 $('publish').onclick=()=>{const keys=[...new Set([...Object.keys(texts),...Object.keys(published)])].filter(k=>JSON.stringify(texts[k])!==JSON.stringify(published[k]));$('review').replaceChildren();for(const k of keys){const item=texts[k]||published[k],p=document.createElement('p'),before=document.createElement('del'),after=document.createElement('ins');before.textContent='Avant : '+(published[k]?.text||item.original);after.textContent='Après : '+(texts[k]?.text||item.original);p.append(before,after);$('review').append(p);}if(!keys.length){notice('Aucune différence avec la version publiée.');return;}$('confirmation').showModal();};
 $('cancel').onclick=()=>$('confirmation').close();$('confirm').onclick=()=>guard(async()=>{if(dirty)await save();const d=await api('publish',{revision});revision=d.revision;published=structuredClone(texts);$('confirmation').close();notice('Textes publiés pour tous. Les observations déjà ouvertes conservent leur version jusqu’à leur prochaine ouverture.');});
 $('restore').onclick=()=>guard(async()=>{if(dirty){notice('Enregistre ton brouillon avant de reprendre une ancienne version.');return;}await api('restore',{revision});await load();notice('Version précédemment publiée reprise en brouillon. Relis-la puis publie si souhaité.');});
 $('activate').onclick=()=>guard(async()=>{const result=await api('activate',{});if(result.authorized){$('identity').hidden=true;await load();$('workspace').hidden=false;$('app').src='/?editor-preview=1';notice('Accès administrateur activé pour ce compte.');}});
 (async()=>{try{const user=await api('identity');if(!user.authorized){$('identity').hidden=false;$('account').textContent='Compte connecté : '+user.email+(user.expectedAccount&&user.email.toLowerCase()!==user.expectedAccount.toLowerCase()?' — ce n’est pas le compte demandé. Déconnecte-toi puis utilise le compte prévu.':'');$('activate').disabled=!user.activationRequired||!!user.expectedAccount&&user.email.toLowerCase()!==user.expectedAccount.toLowerCase();notice(user.activationRequired?'Confirme l’activation avec le compte administrateur.':'L’administration a déjà été activée pour un autre compte.');return;}await load();$('workspace').hidden=false;$('app').src='/?editor-preview=1';notice('Accès administrateur actif. Les visiteurs ne peuvent pas modifier les textes.');}catch(e){notice(e.message+' Ouvre Administration depuis l’application pour te connecter.');}})();})();
