// ASE 2024 prosthetic reference support; descriptive references are not diagnostic cutoffs.
const aseProstheticURL='https://www.asecho.org/wp-content/uploads/2024/01/PIIS0894731723005333.pdf';
function referencePool(key,d){return prostheticReferences.filter(r=>r.valve===key&&r.kind===d.kind)}
function selectedReference(key,d){return referencePool(key,d).find(r=>r.model===d.ref_model&&r.size===d.ref_size)||null}
function enhanceValveSchema(sections,key,mode,d){
 if(mode!=='prosthetic')return sections;
 const pool=referencePool(key,d),models=[...new Set(pool.map(r=>r.model))].sort((a,b)=>a.localeCompare(b));
 const ref=selectedReference(key,d);
 sections[0].fields.push(vs('ref_model','Modèle de référence ASE',models,'Choisir le modèle exact','Vérifier carte de prothèse, position et type ; ne pas assimiler deux générations de dispositifs.'),vs('ref_size','Taille / groupe publié',pool.filter(r=>r.model===d.ref_model).map(r=>[r.size,r.size+(/^\d+(?:-\d+)?$/.test(r.size)?' mm':'')]),'Taille nominale du fabricant','La taille nominale ne correspond pas au diamètre de la chambre de chasse. Certaines références regroupent des tailles.'));
 if(ref)for(const s of sections)for(const f of s.fields){if(['mean','area','vmax','dvi','pht'].includes(f.id)&&ref[f.id])f.ref=ref[f.id]+' '+(f.unit||'')+' — réf. '+ref.table+' (pas un seuil diagnostique)';}
 if(key==='pulmonary'&&!sections.flatMap(s=>s.fields).some(f=>f.id==='area'))sections.find(s=>s.title.startsWith('Hémodynamique')).fields.push(vn('area','Surface effective (EOA)','cm²',ref?.area||'Selon dispositif ; données limitées','Continuité si réalisable, sans fuite significative ni shunt ; comparer à la même méthode dans la référence.'));
 if(key==='aortic'&&['bio','tavi','viv'].includes(d.kind))sections.at(-1).fields.push(vs('svd_grade','Dégénérescence structurelle retenue',['Non établie','Possible — à confirmer','Significative — confirmée par approche intégrée'],'Bioprothèses uniquement','Tableau 6 ASE 2024 ; comparer à 1–3 mois sous PA/fonction VG stables, confirmer les lésions morphologiques et exclure thrombose, endocardite et disproportion.'));
 return sections;
}
function originalPage(page,title){return `<details class="reference-original"><summary>${title} — document original</summary><a href="references/ase2024-p${page}.webp" target="_blank" rel="noopener">Ouvrir / agrandir la page</a><img loading="lazy" src="references/ase2024-p${page}.webp" alt="${title}, ASE 2024, page PDF ${page}"><p>Source : Zoghbi et al., ASE 2024, JASE p. ${page+1}. <a href="${aseProstheticURL}#page=${page}" target="_blank" rel="noopener">Recommandation complète</a>.</p></details>`}
function comparisonHTML(key,d){const ref=selectedReference(key,d);
 if(!ref)return '<p>Choisir le type, le <strong>modèle de référence ASE</strong> et la <strong>taille / groupe publié</strong> dans le premier tableau. Si le dispositif n’est pas répertorié, consulter la référence du fabricant et l’examen initial ; aucune valeur n’est extrapolée.</p>';
 const labels={mean:['Gradient moyen','mmHg'],area:['Surface effective (EOA)','cm²'],vmax:['Vmax','m/s'],dvi:['DVI',''],pht:['PHT','ms']};
 const rows=Object.entries(labels).filter(([id])=>['mean','area'].includes(id)||ref[id]).map(([id,[label,unit]])=>{const n=vNum(d,id);return `<tr><th scope="row">${label}</th><td>${n===null?'Non renseigné':fmt(n)+' '+unit}</td><td>${ref[id]?esc(ref[id])+' '+unit:'Non publiée pour ce modèle / cette taille'}</td></tr>`}).join('');
 return `<p><strong>${esc(ref.model)} · ${esc(ref.size)}${/^\d/.test(ref.size)?' mm':''}</strong> — tableau ${ref.table}, JASE p. ${ref.page+1}.</p><div class="table-wrap"><table class="reference-table"><thead><tr><th>Indice</th><th>Patient</th><th>Valeur publiée</th></tr></thead><tbody>${rows}</tbody></table></div><p class="reference-note">± : moyenne ± écart-type, pas intervalle normal ni seuil de sténose. Parenthèses : intervalle publié (selon étude, médiane / IQR). Vérifier le tableau original. La comparaison à l’examen postopératoire personnel reste indispensable. ${['viv','transcatheter'].includes(d.kind)?'ViV, ViR et ViMAC ne sont pas interchangeables.':''}</p>${originalPage(ref.page,'Référence du dispositif — tableau '+ref.table)}`;
}
function diagnosticTable(headers,rows){return '<div class="table-wrap"><table class="reference-table"><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map((c,i)=>i?'<td>'+c+'</td>':'<th scope="row">'+c+'</th>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function stenosisSupport(key,mode,d){
 let body='',original='',note='Toujours intégrer morphologie, rythme, fréquence cardiaque, charge et débit. Un critère isolé ne suffit pas ; une discordance impose de revoir les acquisitions et de compléter l’imagerie.';
 if(mode==='prosthetic'){
  if(key==='aortic'){
   body=diagnosticTable(['Indice','Normal','Sténose possible','Sténose significative suggérée'],[['Vmax (m/s)','< 3','3 à < 4','≥ 4'],['TA (ms)','< 80','80–100','> 100'],['TA / TE','< 0,32','0,32–0,37','> 0,37'],['SAVR : gradient moyen (mmHg)','< 20','20 à < 35','≥ 35'],['SAVR : DVI','> 0,35','0,25–0,35','< 0,25'],['SAVR : EOA','Référence ± 1 ET','≈ 1 ET sous référence','≈ 2 ET sous référence'],['TAVI : hausse gradient (mmHg)','< 10','10 à < 20','≥ 20'],['TAVI : baisse DVI','< 0,1 ou < 20 %','0,1 à < 0,2 ou 20 à < 40 %','≥ 0,2 ou ≥ 40 %'],['TAVI : baisse EOA','< 0,3 cm² ou < 25 %','0,3 à < 0,6 cm² ou 25 à < 50 %','≥ 0,6 cm² ou ≥ 50 %']]);
   note+=' ASE tableau 5 : associer au moins un critère dépendant du débit (Vmax / gradient) et un indépendant (EOA / DVI). TAVI : variations par rapport à l’ETT initiale stable. L’algorithme de la figure 13 utilise le DVI avec le profil du jet et le temps d’accélération ; ne pas confondre ses branches avec les seuils du tableau.';
   original=originalPage(18,'Sténose prothétique aortique — tableau 5 et algorithme figure 13');
   body+='<h4>Dégénérescence structurelle d’une bioprothèse aortique — tableau 6</h4>'+diagnosticTable(['','Possible','Significative'],[['Voie sténosante','Hausse gradient ≥ 10 mmHg, gradient final ≥ 20, ET baisse EOA ≥ 0,3 cm² ou ≥ 25 % et/ou DVI ≥ 0,1 ou ≥ 20 %','Hausse gradient ≥ 20 mmHg, gradient final ≥ 30, ET baisse EOA ≥ 0,6 cm² ou ≥ 50 % et/ou DVI ≥ 0,2 ou ≥ 40 %'],['Voie régurgitante','Fuite intra-prothétique nouvelle ou majorée ≥ 1 grade, aboutissant à une fuite au moins modérée','Fuite intra-prothétique nouvelle ou majorée ≥ 2 grades, aboutissant à une fuite modérée à sévère ou sévère']])+ '<p class="reference-note">Référence à 1–3 mois, fonction VG et PA stables ; anomalies morphologiques requises. Lésions mixtes : seuils parfois plus bas. Une hausse de gradient seule n’établit pas une dégénérescence. Ces critères ne sont pas transposés aux prothèses mécaniques ni aux autres positions.</p>';
   original+=originalPage(19,'Dégénérescence et disproportion patient–prothèse — tableaux 6 et 7');
  }else if(key==='mitral'){
   body=diagnosticTable(['Indice','Normal','Sténose possible','Sténose significative suggérée'],[['Vmax (m/s)','< 1,9','1,9 à < 2,5','≥ 2,5'],['Gradient moyen (mmHg)','≤ 5','6–10','> 10'],['DVI mitrale / LVOT','< 2,2','2,2–2,5','> 2,5'],['EOA (cm²)','≥ 2','1–2','< 1'],['PHT (ms)','< 130','130–200','> 200']]);
   note+=' Concordance de plusieurs paramètres, à FC physiologique. Hyperdébit, tachycardie et fuite mitrale peuvent augmenter Vmax, gradient et DVI. EOA par continuité, jamais 220/PHT sur prothèse. Le document propose ce tableau, pas un algorithme de sténose équivalent à la figure 13 aortique.';
   original=originalPage(26,'Sténose prothétique mitrale — tableau 11');
  }else if(key==='tricuspid'){
   body=diagnosticTable(['Indice : obstruction suspectée','Bioprothèse','Mécanique'],[['Vmax E (m/s)','≥ 2,1','≥ 1,9'],['Gradient moyen (mmHg)','≥ 9','≥ 6'],['PHT (ms)','≥ 200','≥ 130'],['EOA (cm²)','< 1,5','< 2'],['DVI tricuspide / LVOT','≥ 3,3','≥ 2,1']]);
   note+=' Au moins 5 cycles, hors tachycardie ; respiration, petite taille et hyperdébit influents. DVI sans IA/IT significative. ViV/ViR : gradient > 10 mmHg évocateur de sténose. Ces repères indiquent une suspicion, non un grade automatique.';
   original=originalPage(35,'Sténose prothétique tricuspide — tableau 19');
  }else{
   body=diagnosticTable(['Obstruction possible','Bioprothèse','Homogreffe'],[['Vmax (m/s)','≥ 3,2','≥ 2,5'],['Gradient moyen (mmHg)','≥ 20','≥ 15'],['Autres arguments','Mobilité anormale, turbulence, hausse des gradients au suivi','Localiser au PW : valve, conduit ou branche pulmonaire']]);
   note+=' À VES VD normal ; autres dispositifs : références spécifiques. Retentissement VD et comparaison sériée indispensables. Pas de grade universel de sténose ni de critère de dégénérescence structurelle transposable depuis la valve aortique.';
   original=originalPage(32,'Obstruction prothétique pulmonaire — tableau 15');
  }
 }else{
  if(key==='aortic'){body=diagnosticTable(['Sténose native','Légère','Modérée','Sévère'],[['Vmax (m/s)','2,6–2,9','3,0–3,9','≥ 4'],['Gradient moyen (mmHg)','< 20','20–39','≥ 40'],['Surface (cm²)','> 1,5','1,0–1,5','< 1,0'],['DVI','> 0,50','0,25–0,50','< 0,25']]);note+=' Surface proche de 1 cm² : intégrer la variabilité de mesure. Bas débit : VES indexé ≤ 35 mL/m² ; si gradient bas, confronter FEVG, débit et imagerie complémentaire. <a href="https://www.asecho.org/wp-content/uploads/2017/04/2017ValveStenosisGuideline.pdf#page=12" target="_blank" rel="noopener">ASE/EACVI 2017, tableau 3 et algorithme figure 7</a>.';}
  if(key==='mitral'){body=diagnosticTable(['RM rhumatismal — ASE 2023','Repères'],[['Diagnostic','Morphologie rhumatismale + gradient moyen ≥ 5 mmHg'],['Sténose sévère','Surface ≤ 1,5 cm² ; PHT ≥ 150 ms ; gradient moyen ≥ 10 mmHg'],['Mesure privilégiée','Planimétrie au bout des feuillets ; contrôle 3D si plan oblique']]);note+=' Le gradient dépend de FC/débit ; PHT dépend des compliances. Ne pas transposer sans adaptation au RM dégénératif calcifié. <a href="https://www.asecho.org/wp-content/uploads/2023/01/PIIS0894731722005211.pdf" target="_blank" rel="noopener">ASE 2023 — maladie rhumatismale</a>.';}
  if(key==='tricuspid'){body=diagnosticTable(['Sténose tricuspide significative','Repères concordants'],[['Gradient moyen','≥ 5 mmHg'],['Surface','≤ 1 cm²'],['ITV diastolique','≥ 60 cm'],['PHT','≥ 190 ms']]);note+=' Morphologie, FC et respiration indispensables ; PHT d’appoint. <a href="https://www.asecho.org/wp-content/uploads/2023/01/PIIS0894731722005211.pdf" target="_blank" rel="noopener">ASE 2023 — maladie rhumatismale</a>.';}
  if(key==='pulmonary'){body=diagnosticTable(['Sténose pulmonaire','Légère','Modérée','Sévère'],[['Vmax (m/s)','< 3','3–4','> 4'],['Gradient maximal instantané (mmHg)','< 36','36–64','> 64']]);note+=' Après identification d’un obstacle valvulaire ; exclure obstruction étagée et vitesse proximale élevée. <a href="https://www.asecho.org/guideline/valve-stenosis-2009/" target="_blank" rel="noopener">ASE/EAE 2009 — sténoses valvulaires</a>.';}
 }
 return `<details class="clinical-help" open><summary>Sténose${mode==='prosthetic'?' / obstruction prothétique':''} — tableaux et démarche diagnostique</summary>${body}<p class="reference-note">${note}</p>${original}</details>`;
}
function prostheticSupport(key,mode,d){if(mode!=='prosthetic')return '';const pages={aortic:[50,51,52,53,54,55,56,57],mitral:[57,58,59,60],tricuspid:[61,62],pulmonary:[61]}[key];return `<details class="clinical-help" open><summary>Comparaison au modèle et à la taille — ASE 2024</summary><div id="prosthetic-comparison">${comparisonHTML(key,d)}</div><details><summary>Tous les tableaux originaux pour cette position</summary>${pages.map(p=>originalPage(p,'Valeurs prothétiques de référence')).join('')}</details></details>`}
function refreshReferenceComparison(){const box=document.getElementById('prosthetic-comparison');if(box)box.innerHTML=comparisonHTML(currentValve,valveState[currentValve].prosthetic)}
function pisaTeaching(key){if(key==='pulmonary')return '';return `<details class="clinical-help didactic"><summary>Comment mesurer la PISA et la SOR ?</summary><ol><li>Zoomer sur la convergence en amont de la fuite. Décaler la ligne de base couleur pour obtenir une demi-sphère nette.</li><li>Repère de départ : vitesse d’aliasing ≈ 10 % de la Vmax de fuite, dans les mêmes unités. Exemple : 5 m/s → environ 50 cm/s. Adapter à la géométrie ; ce n’est pas une règle universelle.${key==='tricuspid'?' Pour l’IT, les recommandations utilisent souvent 25–35 cm/s.':''}</li><li>Mesurer le rayon entre l’orifice et la première frontière d’aliasing, pas le diamètre. Choisir la phase correspondant à la Vmax du jet en Doppler continu.</li><li>SOR = 2π × r² × Va / Vmax. r en cm, Va et Vmax en cm/s : résultat en cm² ; multiplier par 100 pour les mm² demandés ici. Volume régurgité = SOR (cm²) × ITV de fuite (cm).</li></ol><p>Exemple pédagogique : r = 0,8 cm, Va = 40 cm/s, Vmax = 500 cm/s → SOR ≈ 32 mm². Ne pas additionner arbitrairement des PISA ; jets multiples, convergence contrainte, orifice elliptique et fuite non holosystolique nécessitent une approche experte. Sur prothèse, les artéfacts réduisent la fiabilité.</p></details>`}
let icuMode=false;
function setICUMode(enabled){icuMode=enabled;document.body.classList.toggle('icu-mode',enabled);document.getElementById('mode-standard').setAttribute('aria-pressed',String(enabled));document.getElementById('mode-complete').setAttribute('aria-pressed',String(!enabled));refreshICUNotice()}
function refreshICUNotice(){const box=document.getElementById('icu-notice');if(!box)return;const count=all.filter(x=>x.advanced&&value(x)!==null).length;box.textContent=icuMode?'Mode réanimation standard : mesures avancées masquées, non effacées. '+(count?count+' valeur(s) avancée(s) déjà saisie(s) reste(nt) incluse(s) dans le compte rendu.':'Le compte rendu reprend toutes les valeurs renseignées.'):'Mode complet : tous les indices sont disponibles.';}
function markAdvancedMeasures(){
 const basic={systole:['tapse','sprime','fac'],diastole:['ea','eeprime','dt','hv_sd'],od:['ra_area','ravi_mod','ravi_al'],lvdiastole:['lv_e','lv_a','lv_ea','lv_dt','lv_es','lv_el','lv_em','lv_ees','lv_eel','lv_eem','lv_tr','lv_pasp']};
 for(const g of groups)for(const sub of g.subs)for(const x of sub.items||[]){x.advanced=/3D/i.test(sub.name)||(g.id==='systole'&&!basic.systole.includes(x.id))||(g.id==='diastole'&&!basic.diastole.includes(x.id))||(g.id==='od'&&(/strain|3D/i.test(sub.name)||['ra_major','ra_minor'].includes(x.id)))||(g.id==='morphology'&&['rvot_plax','rvot_psax','rvot_distal'].includes(x.id))||(g.id==='lvdiastole'&&!x.initial&&!basic.lvdiastole.includes(x.id))||(g.id==='lvsystole'&&['ls_wmsi','ls_gls_previous','ls_gls_change','ls_mapse'].includes(x.id))||(g.id==='og'&&['og_conduit','og_contractile','lv_lars'].includes(x.id));}
}
function initClinicalSupport(){
 document.getElementById('mode-standard').addEventListener('click',()=>setICUMode(true));document.getElementById('mode-complete').addEventListener('click',()=>setICUMode(false));
 document.getElementById('og').insertAdjacentHTML('beforeend','<p class="tab-help">Volume 2D indexé : dilatation légère 35–41, modérée 42–48, sévère > 48 mL/m² (ASE/EACVI 2015, tableau 4). Pour les décimales proches d’un seuil, tenir compte de l’arrondi et de la variabilité. Le volume reflète une charge chronique, pas la volémie aiguë. LASr : normes selon âge, charge et logiciel ; 23–30 % = zone limite. ≤ 18 % est un argument de pressions élevées dans l’algorithme diastolique adapté, pas une norme universelle. FA, IM significative, greffe et sidération atriale limitent cette utilisation. <a href="https://www.asecho.org/wp-content/uploads/2025/04/2015_ChamberQuantificationREV.pdf" target="_blank" rel="noopener">ASE/EACVI 2015</a> · <a href="https://www.asecho.org/wp-content/uploads/2025/11/Strain-2025-Guideline-2.pdf" target="_blank" rel="noopener">ASE/EACVI strain 2025</a>.</p>');
 document.getElementById('lvdiastole').insertAdjacentHTML('afterbegin','<p class="tab-help">Volume OG et strain réservoir : saisie unique dans <button type="button" class="inline-button" onclick="selectTab(\'og\')">Oreillette gauche</button> ; utilisés également pour l’évaluation diastolique VG.</p>');
 document.getElementById('lvsystole').insertAdjacentHTML('beforeend','<details class="clinical-help didactic"><summary>ITV et débit cardiaque — mesure pas à pas</summary><ol><li>Diamètre sous-aortique en parasternal grand axe, en systole, bord interne à bord interne ; saisir en mm.</li><li>Apicale 5 ou 3 cavités : Doppler pulsé dans la chambre de chasse, au même site, avant accélération. Aligner le faisceau, tracer l’enveloppe dense ; moyenner les cycles représentatifs (davantage en FA).</li><li>Saisir l’ITV en cm et la FC initiale. VES = π × (diamètre / 20)² × ITV ; débit = VES × FC / 1000. Indexation automatique à la surface corporelle.</li></ol><p>Le diamètre est élevé au carré : une petite erreur a un effet important. Le débit ne mesure pas la contractilité et n’indique pas, seul, la réponse au remplissage. IA significative, shunt ou obstruction sous-aortique : interprétation limitée.</p></details>');
 document.getElementById('valves').insertAdjacentHTML('afterbegin','<details class="clinical-help didactic"><summary>Repères pratiques — Doppler, DVI et vena contracta</summary><p><strong>Doppler continu :</strong> rechercher la meilleure enveloppe dans plusieurs fenêtres ; tracer le signal dense complet pour le gradient moyen. Un gradient dépend du débit et de la FC.</p><p><strong>DVI :</strong> rapport des ITV, sans diamètre. Aortique : ITV sous-aortique / ITV prothétique. Mitrale ou tricuspide : rapport inverse, ITV prothétique / ITV sous-aortique. Ne pas inverser les seuils.</p><p><strong>Vena contracta :</strong> zoom couleur ; mesurer la partie la plus étroite du jet juste après l’orifice, perpendiculairement au jet. Ne pas mesurer sa largeur dans l’oreillette. Jets multiples ou excentrés : interprétation experte.</p></details>');
 document.addEventListener('input',refreshICUNotice);setICUMode(false);
}
